# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-01 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interpretability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration', models.IntegerField(default=-1)),
                ('method_id', models.IntegerField(default=-1)),
                ('feature_n', models.IntegerField(default=-1)),
                ('property', models.CharField(choices=[(b'T', b'type'), (b'OC', b'occasion'), (b'OP', b'openness'), (b'W', b'width'), (b'M', b'material'), (b'H', b'heel'), (b'C', b'color'), (b'La', b'Laces')], default=b'', max_length=3)),
                ('how_obvious_it_is', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='InterpretabilityGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=-1)),
                ('target_image', models.CharField(default=b'', max_length=128)),
                ('question_order', models.CharField(default=b'', max_length=128)),
                ('iteration', models.IntegerField(default=0)),
                ('code', models.IntegerField(default=-1)),
            ],
        ),
        migrations.AddField(
            model_name='interpretability',
            name='game_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='interpretability.InterpretabilityGame'),
        ),
    ]
