# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-04 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[(b'W', b'woman'), (b'M', b'man'), (b'O', b'prefer not to tell')], max_length=1)),
                ('age', models.CharField(choices=[(b'0', b'less than 18'), (b'1', b'18-23'), (b'2', b'23-27'), (b'3', b'27-35'), (b'4', b'older than 35')], max_length=1)),
                ('carrer_feild', models.CharField(choices=[(b'1', b'Computers and Technology'), (b'2', b'Health Care and Allied Health'), (b'3', b'Education and Social Services'), (b'4', b'Arts and Communications'), (b'5', b'Trades and Transportation'), (b'6', b'Management, Business, and Finance'), (b'7', b'Architecture and Civil Engineering'), (b'8', b'Science'), (b'9', b'Hospitality, Tourism, and the Service Industry'), (b'10', b'Law and Law Enforcement'), (b'11', b'other')], default=b'1', max_length=2)),
                ('expirience_in_online_shopping', models.CharField(choices=[(b'0', b'I am mostly shopping online(make purchases every month)'), (b'1', b'I do online shopping once or twice per year'), (b'2', b'Have never done it')], default=b'0', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, default=None, max_length=20, null=True)),
            ],
        ),
    ]
