# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-04 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comfort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comfort_type', models.CharField(blank=True, default=b'Very comfort', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'target_products/')),
            ],
        ),
        migrations.CreateModel(
            name='ShoeDescriptionByAssessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile', models.IntegerField(default=0)),
                ('image_id', models.IntegerField(default=0)),
                ('style', models.CharField(default=b'-', max_length=128)),
                ('colour', models.CharField(default=b'-', max_length=128)),
                ('material', models.CharField(default=b'-', max_length=128)),
                ('brand_name', models.CharField(default=b'-', max_length=128)),
                ('function', models.CharField(default=b'-', max_length=128)),
                ('short_description', models.TextField(default=b'-')),
                ('comfort', models.ForeignKey(default=b'-', on_delete=django.db.models.deletion.CASCADE, to='shoes.Comfort')),
            ],
        ),
    ]
