# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-04 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoedescriptionbyassessor',
            name='comfort',
            field=models.CharField(choices=[(b'V_C', b'very comfort'), (b'C', b'comfort'), (b'N_C', b'not comfort')], default=b'V_C', max_length=3),
        ),
    ]
