# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-04 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration', models.IntegerField(default=-1)),
                ('feature_n', models.IntegerField(default=0)),
                ('colour_answer', models.IntegerField(default=-1)),
                ('shape_answer', models.IntegerField(default=-1)),
                ('best_image_id', models.IntegerField(default=-1)),
                ('status', models.CharField(default=b'color', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=-1)),
                ('method_id', models.IntegerField(default=-1)),
                ('target_image_id', models.IntegerField(default=-1)),
                ('sucsess', models.IntegerField(default=0)),
                ('step', models.IntegerField(default=0)),
                ('feature_n', models.IntegerField(default=0)),
                ('point', models.IntegerField(default=-1)),
                ('data', models.TextField(default=b'')),
                ('point_features', models.TextField(default=b'')),
                ('iteration', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ImagesInOneLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='OneImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'product/ut-zap50k-images/')),
                ('game_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='search.Game')),
                ('line_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='search.ImagesInOneLine')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='game_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='search.Game'),
        ),
    ]
